services:
  build-image:
    image: atmega-tdd
    command: bash -c "echo build-image completed."
    build: .
  build-hex:
    image: atmega-tdd
    command: bash -c "chmod +x build-app.sh && ./build-app.sh"
    depends_on:
    - build-image
    volumes:
    - ./:/app
  code-complexity:
    image: atmega-tdd
    command: bash -c "chmod +x code-complexity.sh && ./code-complexity.sh"
    depends_on:
    - build-image
    volumes:
    - ./:/app
  static-analysis:
    image: atmega-tdd
    command: bash -c "chmod +x clang-tidy.sh && ./clang-tidy.sh"
    depends_on:
    - build-image
    volumes:
    - ./:/app
  unit-tests:
    image: atmega-tdd
    command: bash -c "chmod +x unit-tests.sh && ./unit-tests.sh"
    depends_on:
    - build-image
    volumes:
    - ./:/app
