name: pre-commit

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: pre-commit/action@v3.0.0
